name: Deploy progress dashboard to Github Pages

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch latest repository
        uses: actions/checkout@v4
      - name: Using Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - name: Setup dependencies
        run: |
          yarn
      - name: Build project
        run: |
          NODE_ENV=production yarn build
      - name: Upload production artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: |
            dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Publishing production artifact
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
